# Generated by Django 5.0.3 on 2024-04-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_info_delete_cred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='glucose_level',
        ),
    ]
